---
- hosts: all
  connection: local
  become: no

  environment:
    PATH: "{{ ansible_env.PATH }}:/sbin:/usr/sbin:/usr/local/homebrew/bin"

  tasks:

  - include_role: name=debug

  - include_role: name=files

  - name: homebrew packages
    homebrew:
      name: "{{ item }}"
      state: present
      update_homebrew: yes
    with_items:
      - ansible
      - cpanminus
      - csshx
      - curl
      - dhcpdump
      - fping
      - git
      - gnupg
      - mtr
      - nmap
      - openssl
      - pinentry-mac
      - pwgen
      - python@2
      - sphinx-doc
      - sqlite
      - tcptraceroute
      - telnet
      - watch
      - xz
      - ykpers

  # it may be necessar to fix up gpg-agent and make sure its working
  # before the following will succeed; just re-run as needed

  - include_role: name=repos

