# see: https://galaxy.ansible.com/singleplatform-eng/users/
---

users:
  - username: "{{ ansible_user_id }}"
    profile: |
      export HISTFILESIZE=10000
      export PATH=$PATH:/usr/local/bin:/usr/local/homebrew/bin
      export PROMPT_COMMAND='echo -ne "\033]0;$(hostname -s)\007"'
      export TERM=vt100
      set -o vi
      # git prompt
      _parse_git_dirty() {
        [[ $(git status --porcelain 2>/dev/null) ]] && echo "*"
      }
      _parse_git_branch() {
        git branch --no-color 2> /dev/null | sed -e '/^[^*]/d' -e "s/* \(.*\)/[\1$(_parse_git_dirty)]/"
      }
      export PS1='\u@\h \[\033[1;33m\]\W\[\033[0m\]$(_parse_git_branch)$ '
      #
      # Launch gpg-agent
      gpg-connect-agent /bye
      # When using SSH support, use the current TTY for passphrase prompts
      gpg-connect-agent updatestartuptty /bye > /dev/null
      # Point the SSH_AUTH_SOCK to the one handled by gpg-agent
      if [ -S $(gpgconf --list-dirs agent-ssh-socket) ]; then
        export SSH_AUTH_SOCK=$(gpgconf --list-dirs agent-ssh-socket)
      else
        echo "$(gpgconf --list-dirs agent-ssh-socket) doesn't exist. Is gpg-agent running ?"
      fi
      export GPG_TTY=$(tty)
      # aliases
      alias ga='pkill -9 gpg-agent && gpg-agent --daemon'
