# see: https://galaxy.ansible.com/singleplatform-eng/users/
---

user_files:
  - profile:
    path: "/Users/{{ ansible_user_id }}/.bash_profile"
    content: |
      export HISTFILESIZE=10000
      export PATH=$PATH:/usr/local/bin:/usr/local/homebrew/bin
      export PROMPT_COMMAND='echo -ne "\033]0;$(hostname -s)\007"'
      export TERM=vt100
      set -o vi
      # git prompt
      _parse_git_dirty() {
        [[ $(git status --porcelain 2>/dev/null) ]] && echo "*"
      }
      _parse_git_branch() {
        git branch --no-color 2> /dev/null | sed -e '/^[^*]/d' -e "s/* \(.*\)/[\1$(_parse_git_dirty)]/"
      }
      export PS1='\u@\h \[\033[1;33m\]\W\[\033[0m\]$(_parse_git_branch)$ '
      #
      # Launch gpg-agent
      gpg-connect-agent /bye
      # When using SSH support, use the current TTY for passphrase prompts
      gpg-connect-agent updatestartuptty /bye > /dev/null
      # Point the SSH_AUTH_SOCK to the one handled by gpg-agent
      if [ -S $(gpgconf --list-dirs agent-ssh-socket) ]; then
        export SSH_AUTH_SOCK=$(gpgconf --list-dirs agent-ssh-socket)
      else
        echo "$(gpgconf --list-dirs agent-ssh-socket) doesn't exist. Is gpg-agent running ?"
      fi
      export GPG_TTY=$(tty)
      # aliases
      alias ga='pkill -9 gpg-agent && gpg-agent --daemon'
  - cdn:
    path: "/Users/{{ ansible_user_id }}/.cdn"
    mode: "0600"
    content: |
      export TO_USER=jtucker
      export TO_PASSWD=XXX
      # ipcdn-ro
      export TRAFFIC_OPS_PASSWD=XXX
  - gitconfig:
    path: "/Users/{{ ansible_user_id }}/.gitconfig"
    mode: "0644"
    content: |
      [http]
        sslVerify = false
      [user]
        name = Jason Tucker
        email = Jason_Tucker@Comcast.com
        signingkey = CACC4D324B45103E
      [push]
        default = simple
      [commit]
        gpgsign = true
      [alias]
        tree = log --graph --all --format=format:'%C(bold blue)%h%C(reset) - %C(bold green)(%ar)%C(reset) %C(white)%s%C(reset) %C(bold white). %an%C(reset)%C(bold yellow)%d%C(reset)' --abbrev-commit --date=relative
  - ssh_config:
    path: "/Users/{{ ansible_user_id }}/.ssh/config"
    mode: "0644"
    content: |
      ServerAliveInterval 60
      UseRoaming no

      Host github.*
        User git

      Host *.comcast.net
        User jtucke01

      Host odol-*
        User jtucke01

      Host cdn*
        User jtucke01

root_files:
  - crontab:
    path: /etc/crontab
    mode: "0644"
    content: |
      @reboot launchctl unload –w /Library/LaunchAgents/net.pulsesecure.pulsetray.plist
