# see: https://galaxy.ansible.com/singleplatform-eng/users/
---

user_files:
  - cdn:
    path: "/Users/{{ ansible_user_id }}/.cdn"
    mode: "0600"
    content: |
      export TO_USER=jtucker
      export TO_PASSWD=XXX
      # ipcdn-ro
      export TRAFFIC_OPS_PASSWD=XXX
  - gitconfig:
    path: "/Users/{{ ansible_user_id }}/.gitconfig"
    mode: "0644"
    content: |
      [http]
        sslVerify = false
      [user]
        name = Jason Tucker
        email = Jason_Tucker@Comcast.com
        signingkey = CACC4D324B45103E
      [push]
        default = simple
      [commit]
        gpgsign = true
      [alias]
        tree = log --graph --all --format=format:'%C(bold blue)%h%C(reset) - %C(bold green)(%ar)%C(reset) %C(white)%s%C(reset) %C(bold white). %an%C(reset)%C(bold yellow)%d%C(reset)' --abbrev-commit --date=relative
  - ssh_config:
    path: "/Users/{{ ansible_user_id }}/.ssh/config"
    mode: "0644"
    content: |
      ServerAliveInterval 60
      UseRoaming no

      Host github.*
        User git

      Host *.comcast.net
        User jtucke01

      Host odol-*
        User jtucke01

      Host cdn*
        User jtucke01

root_files:
  - crontab:
    path: /etc/crontab
    mode: "0644"
    content: |
      @reboot launchctl unload –w /Library/LaunchAgents/net.pulsesecure.pulsetray.plist
