---

- name: ensure .ssh directory
  file:
    path: "/Users/{{ ansible_user_id }}/.ssh"
    state: directory
    mode: 0700

- name: user file content
  blockinfile:
    block: "{{ item.content | default('#') }}"
    dest: "{{ item.path }}"
    mode: "{{ item.mode | default('0600') }}"
    create: true
  with_items: "{{ user_files }}"

- name: root file content
  blockinfile:
    block: "{{ item.content | default('#') }}"
    dest: "{{ item.path }}"
    mode: "{{ item.mode | default('0600') }}"
    create: true
  with_items: "{{ root_files }}"
  become: true

- name: user files
  synchronize:
    checksum: yes
    src: homedir/
    dest: "/Users/{{ ansible_user_id }}"
